var missionArray = [
  "50 Unique Minions",
  "Get any collection to VII (7)",
  "Mining XII (12)",
  "Foraging XV (15)",
  "Farming XII (12)",
  "Combat XII (12)",
  "Alchemy X (10)",
  "Deal 3000 damage in single hit",
  "Obtain any epic pet",
  "Obtain 200k coins",
  "Enchant any sword with 10+ enchants",
  "Collect 20 unique accessories",
  "Get level 4 in any Slayer",
  "Get level 3 in all Slayers",
  "Get Growth V on all armor pieces",
  "Get 80% Crit Chance",
  "Oneshot 4.5k HP Enderman",
  "Upgrade any minion to Tier VII (7)",
  "Level up any pet to 40 lvl",
  "Obtain any Full Dragon Armor",
  "Kill T2 Revenant, Sven, Tarantula",
  "Obtain Radiant Power Orb",
  "Kill 25 Sea Creatures",
  "Collect 30 Fairy Souls",
  "Obtain Uncommon Ring of Love",
  "Obtain Rare Campfire Bagde (1,4k HP)",
  "Make 50k profit on Bazaar Flipping",
  "Fight Magma Cube Boss",
  "Fight Dragon",
  "Place any <a href=\"https://hypixel-skyblock.fandom.com/wiki/Islands\">island</a>",
  "Obtain Super Compactor 3000",
  "Obtain Pig's Foot",
  "Feed your pet with Candy",
  "Craft 4 Medium Storages",
  "Craft Jerry Pet",
  "Kill (any) Revenant Horror using AoTJ",
  "Open Red Gift with random non",
  "Remind Melancholic Viking of the sea",
  "Spend 20k coins on rain",
  "<b>Craft</b> one enchanted wood of every kind",
  "Obtain backpack",
  "Obtain Special rarity item"
];
